version: '3.4'

services:
  ishopweb.api:
    image: ${DOCKER_REGISTRY-}ishopwebapi
    build:
      context: .
      dockerfile: IShopWeb.Api/Dockerfile
    ports:
      - 6000:80
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"